### ISSUE TITLE
Testing tinymce updates

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-UserProfiles#19]
On the tinymce4 branch of UserProfiles, and master of Omeka core, creating and editing is ready for a look.

Admin side: create UP structures, and create profiles for individual users
Public side: edit profiles, and especially check the process across themes and theme settings

**Comment by mebrett** [comment]
General functionality works on public and admin sides. When on the public side, you have the option of not using HTML, but with the box checked tinyMCE displays fine. 

Theme-specific things:  
- Thanks Roy, Emiglio, Big Picture, and Thanks Roy are fine.
- Santa Fe and Berlin have an oddly large space between the heading and the text.
- Rhythm - edit button on the public side only has legible text on hover (otherwise the text is the same color as the button background).
- Center Row is mostly fine, alignment is a little odd. 
- The Daily looks rather weird.
- Seasons: the profile title is a little off in its display.  

Berlin

![berlin](https://user-images.githubusercontent.com/2314070/35992248-be6f2dfe-0cd7-11e8-91d8-94db2aca9061.png)

The Daily: 

![thedaily](https://user-images.githubusercontent.com/2314070/35992200-9d278cf4-0cd7-11e8-9528-ecef48a17d84.png)

Seasons:

![screen shot 2018-02-08 at 1 44 52 pm](https://user-images.githubusercontent.com/2314070/35992271-d19723e6-0cd7-11e8-8f4d-afbb6b375327.png)

**Comment by patrickmj** [comment]
Latest on tinymce4 addresses some the issues, but the cross-theme compatibility is something I'll need to consult with @kimisgold  about.

**Comment by patrickmj** [comment]
The buttons on the public edit page are also a thing to look in to.

**Comment by mebrett** [comment]
One problem which I think straddles this issue and #20 is the placement of the "use html" checkbox on most themes - if you have multiple inputs, it ends up under the "remove" button in such a way that it looks like it's associated with the element below rather than above. 

Ex. 
<img width="512" alt="screen shot 2018-02-14 at 2 13 19 pm" src="https://user-images.githubusercontent.com/2314070/36223074-40d0f3be-1191-11e8-874a-7bb194ff8703.png">

**Comment by zerocrates** [comment]
do we have a sense of our status here?

**Comment by patrickmj** [comment]
Theme wonkiness that I'm not sure how to address, but no complaints about the tinymce stuff. So, if we really want to make sure something is out there that matches the core tinymce change we could probably release it then do another quick release after we fix the styling (I don't really know when the styling got busted, but it seem unrelated to the tinymce stuff)

**Comment by patrickmj** [comment]
@zerocrates From the stuff in #20, looks like this might need a serious rewrite. The original intent was to intrude as little as possible on how the theme wants things to look. However, little special pieces of CSS needed to get inserted here and there. Now, it looks like we need to bail on that idea and force everything into how the plugin demands things to work.
